### PR TITLE
Changing loader.js to being bower loaded

### PR DESCRIPTION
**Pull request by csprocket777**
I am replicating the changes from another fork that allowed me to successfully install and use this library. I have installed the results of this PR in my project and find it to be compiling fine.

### CODE REVIEW

**Comment by kurko** [comment]
Perfect, @csprocket777. Do you mind squashing the commits? These are duplicated there.

Thank you very much! Will check this today on my app.

**Comment by csprocket777** [comment]
I think I squashed it correctly. Don't do this too often.

**Comment by kurko** [comment]
I'll do it for you this evening :smile: 

Basically, you have 3 commits, so you can run `git reset --soft HEAD~3`. Then commit again.

**Comment by kurko** [comment]
#25 was the same change :grin:

**Pull request closed without merging**
